### ISSUE TITLE
question about parameter correct_deg:0.195 in run_kitti.yaml

### ISSUE THREAD

**Issue by Zhangjyhhh** [PRBonn/PIN_SLAM#11]
Thanks for your excellent work!!!!!!!!!
For kitti dataset, there is a parameter named correct_deg 0.195. I wanna ask what is the purpose of this parameter, and why is this parameter 0.195?

**Comment by YuePanEdward** [comment]
Thanks for your kind words.
The KITTI odometry dataset has an intrinsic calibration problem on the vertical angle of each laser beam. The author of IMLS-SLAM proposed this small beam-wise vertical angle correction to cope with the distortion. The same correction is used in CT-ICP, KISS-ICP, MULLS, etc. and is now a regular operation for the benchmarking on KITTI. This angle correction is commonly set as 0.195 or 0.205. Hope this can solve your concerns.
