### ISSUE TITLE
LiDAR points and Visual RGB

### ISSUE THREAD

**Issue by zhSlamer** [PRBonn/PIN_SLAM#14]
Thank you for your wonderful work！

1. How to integrate LiDAR point clouds with visual RGB?
2. Is there a recommended dataset?

Thank you!

**Comment by YuePanEdward** [comment]
Thank you very much for your interest in our work and thanks for your kind words.

1. One needs a calibrated LiDAR-camera system (better to have the same FOV). Then you can project the LiDAR point cloud to the image frame and try to interpolate the color of the nearby pixels. By doing so, you can get a colorized point cloud.
2. For the publicly available datasets, you may try the [R3Live dataset](https://github.com/ziv-lin/r3live_dataset).
