### ISSUE TITLE
About the VBR dataset

### ISSUE THREAD

**Issue by Louis-Leee** [PRBonn/PIN_SLAM#19]
Hi, thanks for your impressive work. I see there is a run_vbr.yaml in config folder. But after I download the VBR dataset, there is no /ply folder, so I just want to ask, if you do some convert processing on vbr dataset, using like scripts/rosbag2ply.py? Additionally in each scene in vbr, there are several .bag, how do you combine them?

Thanks for your early reply.

**Comment by YuePanEdward** [comment]
Thanks for your interest in our work.

Indeed, one solution would be using scripts/rosbag2ply.py and a shell script to convert all the rosbags.
However, as you can imagine, this is a bit cumbersome.

Now the walkaround is to use the kiss-icp dataloader. The current version of PIN-SLAM supports to use the kiss-icp data loader. You may add (edit) the following contents to the config file:

```
setting:
  .....
  use_kiss_icp_dataloader: True
  pc_path: "./data/vbr/vbr_slam/spagna/spagna_test0" # or other sequences
  .....
```

For using the kiss-icp data loader, install kiss-icp by:
```
pip install kiss-icp
```

Then simply run:
```
python pin_slam.py ./config/lidar_slam/run_vbr.yaml rosbag /ouster/points
```

Currently, this rosbag dataloader does not support the loading of ground truth poses.
Therefore, you need to evaluate the results after the SLAM.

Here are some sample results that you can achieve with PIN-SLAM on the cool Rome dataset:


![closoum_example_pin](https://github.com/PRBonn/PIN_SLAM/assets/34207278/00b333a1-1bb6-4c28-9fd4-44f6d27ca4af)
