### ISSUE TITLE
poor result on new college dataset.

### ISSUE THREAD

**Issue by Zhangjyhhh** [PRBonn/PIN_SLAM#26]
Hi, Thanks for your excellent work !!!
I want to know how to get better result as your paper in TABLE XI on Quad. I use the default config file: ./config/Lidar_slam/run_ncd.yaml. i generate mesh use command " python vis_pin_map.py ./experiments/ncd_****  0.2 nueral_points.ply mesh_20cm.ply".  and  here is my result:

Predicted mesh unifrom sample:  10000000  -->  8563620  ( 0.02 m)
{'MAE_accuracy (m)': 0.16234044696769342, 'MAE_completeness (m)': 0.1927699826745742, 'Chamfer_L1 (m)': 0.17755521482113382, 'Chamfer_L2 (m)': 0.23996385734393333, 'Precision [Accuracy] (%)': 64.42148915027659, 'Recall [Completeness] (%)': 62.22490167539342, 'F-score (%)': 63.304146324647974, 'Spacing (m)': 0.02, 'Inlier_threshold (m)': 0.2, 'Outlier_truncation_acc (m)': 0.4, 'Outlier_truncation_com (m)': 2.0}

could you please tell me how  can get the same result as you.
here are the mesh and my config file screenshot:
![Screenshot from 2024-07-24 11-21-58](https://github.com/user-attachments/assets/e14ee2f4-4c96-419f-bb89-b15611aa6714)
![Screenshot from 2024-07-24 11-23-08](https://github.com/user-attachments/assets/96e39f80-1c5d-459e-b527-a4311482f791)

**Comment by YuePanEdward** [comment]
Hi, thanks for your interest in our work.

Here are the [meshes](https://uni-bonn.sciebo.de/s/TeyiZZg8bNbaUAP) I got for the NCD02_Quad mapping experiment. This folder includes the meshes of PIN-SLAM and two baseline methods (NKSR with KISS-ICP poses and SLAMesh). Numbers of the other four baseline methods are reported by Nerf-LOAM.

PIN-SLAM's evaluation results are:
```
MAE_accuracy (m),MAE_completeness (m),Chamfer_L1 (m),Chamfer_L2 (m),Precision [Accuracy] (%),Recall [Completeness] (%),F-score (%),Spacing (m),Inlier_threshold (m),Outlier_truncation_acc (m),Outlier_truncation_com (m)
0.11552514390375901,0.15247310990752128,0.13399912690564014,0.22192155677537126,83.47852386868307,80.73416443483003,82.08341197526036,0.02,0.2,0.4,2.0
```

We generally increase the iteration numbers for mapping, and increase the training data pool capacity. This would not affect the pose estimation accuracy but would slightly improve the reconstruction quality.

**Comment by Zhangjyhhh** [comment]
> Hi, thanks for your interest in our work.
> 
> Here are the [meshes](https://uni-bonn.sciebo.de/s/TeyiZZg8bNbaUAP) I got for the NCD02_Quad mapping experiment. This folder includes the meshes of PIN-SLAM and two baseline methods (NKSR with KISS-ICP poses and SLAMesh). Numbers of the other four baseline methods are reported by Nerf-LOAM.
> 
> PIN-SLAM's evaluation results are:
> 
> ```
> MAE_accuracy (m),MAE_completeness (m),Chamfer_L1 (m),Chamfer_L2 (m),Precision [Accuracy] (%),Recall [Completeness] (%),F-score (%),Spacing (m),Inlier_threshold (m),Outlier_truncation_acc (m),Outlier_truncation_com (m)
> 0.11552514390375901,0.15247310990752128,0.13399912690564014,0.22192155677537126,83.47852386868307,80.73416443483003,82.08341197526036,0.02,0.2,0.4,2.0
> ```
> 
> We generally increase the iteration numbers for mapping, and increase the training data pool capacity. This would not affect the pose estimation accuracy but would slightly improve the reconstruction quality.

thanks for your quick reply
