### ISSUE TITLE
IndexError: 'neighb_idx' is out of bounds for dimension 0 when extracting mesh after completing SLAM run

### ISSUE THREAD

**Issue by asda-cmd** [PRBonn/PIN_SLAM#27]
Hi there, thanks for your work! I just encountered a problem when the algorithm extracted mesh when it was finishing.
I first extract .ply files from rosbag using rosbag2ply.py, and I give .ply directory to the run_ncd_128.yaml file. Then I start the program by running the following command:
`python pin_slam.py /home/user/PIN_SLAM/config/lidar_slam/run_ncd_128.yaml -smc`
When the SLAM is finished and started to extract mesh, it gives the following error shown in the image happens in this [line](https://github.com/PRBonn/PIN_SLAM/blob/c72f1b0ac9e8e4da50f032a81dfc645360a01785/model/neural_points.py#L888) 
![Screenshot from 2024-08-21 01-04-46](https://github.com/user-attachments/assets/b912e30f-de42-474d-86fb-970e1d24a9f0)

I also tried to run it on the GPU, it also gives the same error. This error only comes up in some of the datasets (e.g. newer college dataset sequence 02 long experiment with the parameter of run_ncd.yaml; and sequence Cloister in Newer College Dataset with the parameter of run_ncd_128.yaml. Math institute easy works fine)

I also tried to add following code just above this [line](https://github.com/PRBonn/PIN_SLAM/blob/c72f1b0ac9e8e4da50f032a81dfc645360a01785/model/neural_points.py#L888) 
```
invalid_indices_mask = neighb_idx >= self.neural_points.shape[0]
neighb_idx[invalid_indices_mask] = -1
```

However, it only reconstructs parts of the mesh (left: mesh extracted from PIN-SLAM, right: gt)

![Screenshot from 2024-08-21 01-27-23](https://github.com/user-attachments/assets/c1c969ca-bfda-4bc5-9cbd-c9622e003025)

Thanks!

**Comment by YuePanEdward** [comment]
Thank you very much for reporting the bug.

I guess the cause of the bug is as follows: 

In `pin_slam.py`, the order of the following two lines of codes is incorrect:
```
neural_points.recreate_hash(None, None, False, False) # merge the final neural point map 
neural_points.prune_map(config.max_prune_certainty, 0) # prune uncertain points for the final output    
```
, which should be:

```
neural_points.prune_map(config.max_prune_certainty, 0) # prune uncertain points for the final output   
neural_points.recreate_hash(None, None, False, False) # merge the final neural point map 
```
If we prune some points after recreating the hash indexing, the hash indexing might be out of the bound during the global mesh reconstruction. 
I will push the updated version soon.

For the mesh visualization, you may also turn on the visualizer by adding the `-v` flag when running the code.

**Comment by asda-cmd** [comment]
Thanks for your quick reply! Now the problem has been solved.
