### ISSUE TITLE
MaiCity01

### ISSUE THREAD

**Issue by whwh747** [PRBonn/PIN_SLAM#28]
Thank you for open-sourcing such an excellent work. May I ask why I got such a result on the MaiCity01 sequence? I ran this sequence using `python3 pin_slam.py -i dataset_path -vsm`.

**Comment by whwh747** [comment]
![微信截图_20240905112853](https://github.com/user-attachments/assets/daf35429-817c-4f6f-9f1e-2583d9ee4254)

**Comment by YuePanEdward** [comment]
Thanks for your interest in our work. 

The simulation of the poses in MaiCity does not obey the common kinematics of robots. The car moves 1m without acceleration at the beginning of the sequence, indicating the car's acceleration is 20g, which is unrealistic. PIN-SLAM relies on the simple uniform motion model for the kinematic initial guess. It would lose track in the beginning and corrupt the map with the default configuration.  

To cope with this issue, you can edit the following lines in the config file (in your case, the default one `config/lidar_slam/run.yaml`:
```
setting:
  deskew: False # MaiCity didn't simulate the motion distortion
  kitti_correct: True # provide a initial guess of motion along x-axis for the first frame
```
You can get the following result:

![issue#28_pin_slam_for_maicty](https://github.com/user-attachments/assets/88b5433f-0329-4ca2-a1b5-dd6a103c11d5)

**Comment by whwh747** [comment]
thank you very much! i got it!
