### ISSUE TITLE
Attitude drift after making a turn in custom dataset

### ISSUE THREAD

**Issue by qpc001** [PRBonn/PIN_SLAM#3]
Top(at time 1):
![image](https://github.com/PRBonn/PIN_SLAM/assets/31476516/f817ff0c-390c-48ce-ab02-63ca1e1ca2fb)

Side(at time 1):
![image](https://github.com/PRBonn/PIN_SLAM/assets/31476516/e5bb9547-1ef6-482d-b674-328a1e5a3c14)

Side(at time 2):
![image](https://github.com/PRBonn/PIN_SLAM/assets/31476516/9266f827-fdcc-40f5-87f7-965ee2d98548)

It will make a z drift and increase unbound

**Comment by YuePanEdward** [comment]
Thanks for your interest in our project.
I think some parameter tuning might be needed. The `run_ros_general.yaml` config file is just a default starting point.
Is it possible for you to share the ROS bag with me so that I can have a close look?

**Comment by YuePanEdward** [comment]
Thanks for sending me the data.
I am using the current default config file `run_ros_general.yaml `.

```
python pin_slam_ros.py ./config/lidar_slam/run_ros_general.yaml /top/rslidar_points timestamp
```

Here's the result I got in Rviz:

![issue3_rviz_result](https://github.com/PRBonn/PIN_SLAM/assets/34207278/221283a5-47a4-439b-9a6e-0366854ab522)

Here's the reconstructed mesh (inspected by `python vis_pin_map.py`) and the neural point map:


![issue3_mesh_30cm_mc](https://github.com/PRBonn/PIN_SLAM/assets/34207278/df532c55-3948-4a8b-82c0-49d0cfcd1a6f)
![issue3_neural_points](https://github.com/PRBonn/PIN_SLAM/assets/34207278/669717ee-c543-41da-bdae-d3d809eb2ad5)

You may also try it.

**Comment by YuePanEdward** [comment]
You may need to play back the rosbag with a lower rate if your GPU is not powerful enough.

**Comment by YuePanEdward** [comment]
I see. It's a bit weird, I corrected 8 loops from my side. 

![issue3_loop](https://github.com/PRBonn/PIN_SLAM/assets/34207278/f785dde1-bb28-4ca8-8be9-3516389c4cae)

You may pull the latest code and try again.

Besides, from the log, it seems that the LiDAR undistortion is not enabled. 

You may use  `timestamp` instead of `time` as the point-wise timestamp field.

**Comment by YuePanEdward** [comment]
It's great that you get the expected map.

For the consuming time, here's my result on a single A4000 GPU:
![time_details](https://github.com/PRBonn/PIN_SLAM/assets/34207278/56a7481f-8287-4d0d-8fa2-b0c939348ad6)

The average consuming time is about 105ms per frame (excluding the data IO and message publishing time).

**Comment by YuePanEdward** [comment]
It's a bit weird. Here's the result I got:
![issue3_demo_run_timing](https://github.com/PRBonn/PIN_SLAM/assets/34207278/bb578355-add9-4aaa-8f47-4471cacb06a5)

Note that for the first frame, we train for 40x more iterations than the later frames for map initialization.
