### ISSUE TITLE
eval issue

### ISSUE THREAD

**Issue by whwh747** [PRBonn/PIN_SLAM#30]
Thank you for your excellent work. I have a question: I ran the maicity01 sequence multiple times, but each time the resulting mesh and pose were exactly the same. What could be the reason for this?
![image](https://github.com/user-attachments/assets/123368aa-d0af-4bd4-87ef-803090d8e7fa)

**Comment by whwh747** [comment]
i find same issue in ncd dataset，Could there be an issue with my settings? I believe the results shouldn't be the same each time I run it.

**Comment by YuePanEdward** [comment]
We fix the random seed for each run (by default, 42). Therefore, the results would be most of the time the same. To set a different random seed, you can add the flag  —seed 2024 (or other numbers) upon running.

**Comment by whwh747** [comment]
thank you！



发自我的iPhone


------------------ Original ------------------
From: Yue Pan ***@***.***&gt;
Date: Sat,Sep 7,2024 4:07 PM
To: PRBonn/PIN_SLAM ***@***.***&gt;
Cc: whwhwh ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [PRBonn/PIN_SLAM] eval issue (Issue #30)





 
We fix the random seed for each run (by default, 42). Therefore, the results would be most of the time the same. To set a different random seed, you can add the flag  —seed 2024 (or other numbers) upon running.
