### ISSUE TITLE
How to inspect the pre-trained results using Rerun software.

### ISSUE THREAD

**Issue by ssssshwan** [PRBonn/PIN_SLAM#32]
Hi, thanks for the great work and for making the code available.

I was wondering if there is any code available to inspect the pre-trained results (i.e., pin_map.pth) using Rerun software. I am specifically working with the Replica dataset.

**Comment by YuePanEdward** [comment]
Thanks for your interest in our work.

Currently, we don't support PIN Map offline visualization using Rerun. You can use `vis_pin_map.py` to visualize the neural point map and mesh map after the SLAM process. I will consider support Rerun for that purpose in the future. Any PR on this topic is also welcomed.
