### ISSUE TITLE
How to use Replica dataset

### ISSUE THREAD

**Issue by small-zeng** [PRBonn/PIN_SLAM#7]

**Comment by small-zeng** [comment]
Thanks for your nice work, can you provide your replica data with format of your paper ?

**Comment by YuePanEdward** [comment]
Thanks for your interest in our work. 
You can use this [script](https://github.com/PRBonn/PIN_SLAM/blob/main/scripts/convert_replica.sh) to convert the replica dataset to the desired format of PIN-SLAM.
