### ISSUE TITLE
signal frame

### ISSUE THREAD

**Issue by lzbushicai** [PRBonn/PIN_SLAM#8]
Thank you for your work. I would like to rebuild a mesh with point clouds for each of my frames and save it. Is this project feasible?
Mesh should be generated based on the completed sequence, rather than directly using a single frame point cloud to generate mesh？

**Comment by YuePanEdward** [comment]
Thanks for your interest in our work.
Yes, it‘s possible to do so.
PIN SLAM would output a neural point map after finishing the whole data sequence.
With this neural point map, you can rebuild the mesh within any bounding box.
One possible solution is to edit the script [vis_pin_map.py](https://github.com/PRBonn/PIN_SLAM/blob/main/vis_pin_map.py).

For example, you can use the command: 
``` python vis_pin_map.py [path/to/your/result/folder] [marching_cubes_resolution_m] [(cropped)_map_file.ply]  [output_mesh_file.ply] [mc_nn_threshold] ```
and use the point cloud of each frame under the world frame as the ` (cropped)_map_file.ply `.

**Comment by lzbushicai** [comment]
Thank you for your reply. I'm sorry that I haven't looked at github recently. Since I still need to resample the created mesh and retain semantic information, I adopted other solutions, but your solution is still great! ! ! !
